### PR TITLE
[bug 1337800] replace docker with docker_container

### PR DESCRIPTION
**Pull request by TannerFilip**

### CODE REVIEW

**Comment by johngian** [comment]
ok to test

**Review by akatsoulas — APPROVED** [review]

**Comment by akatsoulas** [comment]
@TannerFilip can you do a quick rebase?

**Comment by TannerFilip** [comment]
@akatsoulas should be done

**Comment by akatsoulas** [comment]
@TannerFilip I opened PR #131 which is basically your commit with a rebase to master. The only difference with this PR is that you have two commits with the latest changes in master fetched into this PR whereas on the other PR the commit is updated (rebased) with the latest changes to master. I am closing this PR in favor of #131. Thanks again for fixing this!

**Pull request closed without merging**
