### PR TITLE
Add project README file with essential information.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
@flamingspaz r?
This is an initial take on some missing essential docs in our repo.

**Comment by flamingspaz** [comment]
Looks good. Maybe we should also list the galaxy modules that we use?

**Comment by johngian** [comment]
@flamingspaz PR updated

**Comment by johngian** [comment]
r?

**Comment by flamingspaz** [comment]
r+

**Pull request merged**
