### PR TITLE
[bug 1283458] standardize file names to .yml

### PR DESCRIPTION
**Pull request by TannerFilip**

### CODE REVIEW

**Comment by flamingspaz** [comment]
The inventory files are ini-style so I don't think they should be .yml

What do you think nemo?

**Comment by TannerFilip** [comment]
I've reverted that change, they probably shouldn't be yml if it's ini

**Comment by johngian** [comment]
Code looks OK. I also suggest we rename `group_vars/openvpn` to `group_vars/openvpn_secrets` for consistency.

**Comment by johngian** [comment]
test this please

**Comment by johngian** [comment]
Hey @TannerFilip

Is there any update with that? Let me know if you need any help.

**Comment by TannerFilip** [comment]
Sorry, totally missed that comment. I'll be able to get that in the next couple days, don't have a ton of time right now

**Pull request closed without merging**
