### PR TITLE
Configure quorum in all gluster volumes.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
@flamingspaz r?

**Comment by flamingspaz** [comment]
Should we set `cluster.server-quorum-type` too?

**Comment by johngian** [comment]
I guess? /me checking

**Comment by johngian** [comment]
test this please

**Comment by johngian** [comment]
@flamingspaz PR updated

**Comment by flamingspaz** [comment]
r+ if check passes

**Comment by flamingspaz** [comment]
Actually, it needs an ansible tag and a handler for restarting gluster.

**Pull request closed without merging**
