### PR TITLE
Fix inventory

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
@flamingspaz Can you take a look at this?

**Comment by johngian** [comment]
The idea is to remove the complexity of the roles introduces because of the different envs. The only change that we need to do is to add more specific tags (eg `mesosmasterprod`) to recognize the instances.

**Comment by flamingspaz** [comment]
I like the idea of using static groups but I'm not sure if it's worth messing up the tags for slightly less complex code. We may end up using the same tags to configure consul/sensu/others and splitting environments on the app tag might not work as well for those. Maybe we could have a mesos_env tag to deal with this?

(It seems like what we want [isn't yet available](https://github.com/ansible/ansible/issues/10131)).

**Comment by johngian** [comment]
For me its much better to have more specific tags just to identify our ansible groups instead of repeating the same code for different envs. Its much harder to maintain duplicate code and its **really** prone to errors.

**Comment by flamingspaz** [comment]
Makes sense, lets go for it.

**Pull request merged**
