### PR TITLE
Add tag to name to workaround ansible bug

### PR DESCRIPTION
**Pull request by flamingspaz**
- Add ansible tags

### CODE REVIEW

**Comment by johngian** [comment]
Please add a comment here to mention that it's an ansible bug and describe the workaround.

**Comment by johngian** [comment]
r+wc

**Comment by johngian** [comment]
And it might be worth it to open an issue in ansible for that. Docs mention that tag is optional.

**Comment by flamingspaz** [comment]
when adding the tag to just the `tag` param on the image pull task it still tries to pull the `latest` tag. Adding the tag to both the `name` and `tag` params seems to solve the issue.

**Comment by johngian** [comment]
r+

**Pull request merged**
