### PR TITLE
Fix jenkins gluster mountpoint.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
This bug was introduced after `jenkins` mountpoint got corrupted. At the moment we are using `partinfra_jenkins`. Let's change this in the playbooks to reflect the current state.

**Comment by johngian** [comment]
@flamingspaz r?

**Comment by flamingspaz** [comment]
r+

**Comment by johngian** [comment]
test this please

**Comment by johngian** [comment]
test this please

**Comment by johngian** [comment]
test this please

**Pull request merged**
