### PR TITLE
[bug 1236483] Add role to facilitate for cluster root emails.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
@flamingspaz r?

**Comment by johngian** [comment]
Closing this one for now. Let's revisit monitoring in another PR.

**Comment by johngian** [comment]
Closing this one for now. Let's revisit monitoring in another PR.

**Comment by johngian** [comment]
test this please

**Comment by johngian** [comment]
retest this please

**Comment by flamingspaz** [comment]
r+

**Pull request merged**
